version: '3.4'

networks:
  blogbackend:
  blogfrontend:

services:
  sql:
    container_name: blog_sql
    image: "mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04"
    ports:
      - 8080:1433 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Senha@123
      - MSSQL_PID=Express
    networks:
      - blogbackend
    volumes:
      - sql_data:/var/opt/mssql

  api:
    container_name: blog_api
    image: blog-api
    build:
      context: src/Services/Blog
      dockerfile: ./1-Api/Api/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - sql
    environment:
      - DB_HOST=blog_sql
      - DB_NAME=BlogApp
      - DB_SA_PASSWORD=Senha@123
    networks:
      - blogbackend
      - blogfrontend
  
  spa:
    container_name: blog_spa
    image: blog-spa
    build:
      context: src/Web/WebSPA/Blog
      dockerfile: ./Dockerfile
    ports:
      - 8082:80
    depends_on:
      - api
    networks:
      - blogfrontend

volumes:
  sql_data:
